whitelist:
  - "CLASS;;铸刃者情报"
  - "WEAPON;;神圣之剑"

gui:
  title: "&8物品升级界面"
  size: 27
  decorative-slots:
    "[0,1,2,3,5,6,7,8]":
      material: GRAY_STAINED_GLASS_PANE
      name: "&7"
    "[18,26]":
      material: LIGHT_GRAY_STAINED_GLASS_PANE
      name: "&8边缘"
      lore:
        - "&7这只是个边框"
  close-button-slot: 22
  close-button:
    material: BARRIER
    name: "&c关闭升级界面"
    lore:
      - "&7点击关闭界面"

debug-level: INFO
