name: DrcomoUpgradeGUIMI
version: '1.0'
main: cn.drcomo.drcomoupgradeguimi.DrcomoUpgradeGUIMI
api-version: '1.18'
authors: [ BaiMo_ ]
commands:
  drcomoupgrade:
    description: Upgrade items or reload config
    usage: /<command> [open|reload]
